// ── ITEM LIBRARY ────────────────────────────────────────────────────────────
// Edit this file to add, remove, or modify items.
//
// Fields:
//   name          (required) string
//   bulk          (required) Bulk.PACKABLE | Bulk.STOCK | Bulk.BULKY
//   description   (optional) HTML string shown in the inspector
//   cost          (optional) string shown in the inspector, e.g. "50 gp"
//   dmOnly        (optional) true → hidden from players' autocomplete
//   noCarry       (optional) true → doesn't count toward carry capacity
//   containerRows (optional) number → item acts as a container with this many rows
//   variables     (optional) { key: { value, control, min, max } } → tracked counters

window.Bulk = {
  PACKABLE:  { id: 'packable'  },
  STOCK:     { id: 'stock'     },
  BULKY:     { id: 'bulky'     },
};

// Weapon list used by magical weapon items — update here to add new weapon types
window.WEAPON_OPTIONS = [
  "Club","Dagger","Greatclub","Handaxe","Javelin","Light Hammer","Mace",
  "Quarterstaff","Sickle","Spear","Dart","Light Crossbow","Shortbow","Sling",
  "Battleaxe","Flail","Glaive","Greataxe","Greatsword","Halberd","Lance",
  "Longsword","Maul","Morningstar","Pike","Rapier","Scimitar","Shortsword",
  "Trident","Warhammer","War Pick","Whip","Blowgun","Hand Crossbow",
  "Heavy Crossbow","Longbow",
];

window.ITEM_LIBRARY = [

  { _section: "Simple Weapons" },
  // ── SIMPLE MELEE — LIGHT THROWN (2 gp, Packable) ────────────────────────
  { name: "Dagger",       bulk: Bulk.PACKABLE, cost: "2 gp",  description: `<i>Simple Melee Weapon</i><br>1d4 Piercing &mdash; Finesse, Light, Thrown (20/60) &bull; Mastery: Nick` },
  { name: "Handaxe",      bulk: Bulk.PACKABLE, cost: "2 gp",  description: `<i>Simple Melee Weapon</i><br>1d6 Slashing &mdash; Light, Thrown (20/60) &bull; Mastery: Vex` },
  { name: "Light Hammer", bulk: Bulk.PACKABLE, cost: "2 gp",  description: `<i>Simple Melee Weapon</i><br>1d4 Bludgeoning &mdash; Light, Thrown (20/60) &bull; Mastery: Nick` },

  // ── SIMPLE MELEE — LIGHT (5 gp, Stock) ──────────────────────────────────
  { name: "Club",         bulk: Bulk.STOCK,    cost: "5 gp",  description: `<i>Simple Melee Weapon</i><br>1d4 Bludgeoning &mdash; Light &bull; Mastery: Slow` },
  { name: "Sickle",       bulk: Bulk.STOCK,    cost: "5 gp",  description: `<i>Simple Melee Weapon</i><br>1d4 Slashing &mdash; Light &bull; Mastery: Nick` },

  // ── SIMPLE MELEE — STANDARD (10 gp, Stock) ──────────────────────────────
  { name: "Javelin",      bulk: Bulk.STOCK,    cost: "10 gp", description: `<i>Simple Melee Weapon</i><br>1d6 Piercing &mdash; Thrown (30/120) &bull; Mastery: Slow` },
  { name: "Mace",         bulk: Bulk.STOCK,    cost: "10 gp", description: `<i>Simple Melee Weapon</i><br>1d6 Bludgeoning &bull; Mastery: Sap` },
  { name: "Quarterstaff", bulk: Bulk.STOCK,    cost: "10 gp", description: `<i>Simple Melee Weapon</i><br>1d6 Bludgeoning &mdash; Versatile (1d8) &bull; Mastery: Topple` },
  { name: "Spear",        bulk: Bulk.STOCK,    cost: "10 gp", description: `<i>Simple Melee Weapon</i><br>1d6 Piercing &mdash; Thrown (20/60), Versatile (1d8) &bull; Mastery: Sap` },

  // ── SIMPLE MELEE — TWO-HANDED (15 gp, Stock) ────────────────────────────
  { name: "Greatclub",    bulk: Bulk.STOCK,    cost: "15 gp", description: `<i>Simple Melee Weapon</i><br>1d8 Bludgeoning &mdash; Two-Handed &bull; Mastery: Push` },

  // ── SIMPLE RANGED (15 gp, Stock) ────────────────────────────────────────
  { name: "Dart",          bulk: Bulk.STOCK,   cost: "15 gp", description: `<i>Simple Ranged Weapon</i><br>1d4 Piercing &mdash; Finesse, Thrown (20/60) &bull; Mastery: Vex` },
  { name: "Light Crossbow",bulk: Bulk.STOCK,   cost: "15 gp", description: `<i>Simple Ranged Weapon</i><br>1d8 Piercing &mdash; Ammunition (80/320), Loading, Two-Handed &bull; Mastery: Slow` },
  { name: "Shortbow",      bulk: Bulk.STOCK,   cost: "15 gp", description: `<i>Simple Ranged Weapon</i><br>1d6 Piercing &mdash; Ammunition (80/320), Two-Handed &bull; Mastery: Vex` },
  { name: "Sling",         bulk: Bulk.STOCK,   cost: "15 gp", description: `<i>Simple Ranged Weapon</i><br>1d4 Bludgeoning &mdash; Ammunition (30/120) &bull; Mastery: Slow` },

  { _section: "Martial Weapons" },
  // ── MARTIAL MELEE — LIGHT (20 gp, Stock) ────────────────────────────────
  { name: "Scimitar",     bulk: Bulk.STOCK,    cost: "20 gp", description: `<i>Martial Melee Weapon</i><br>1d6 Slashing &mdash; Finesse, Light &bull; Mastery: Nick` },
  { name: "Shortsword",   bulk: Bulk.STOCK,    cost: "20 gp", description: `<i>Martial Melee Weapon</i><br>1d6 Piercing &mdash; Finesse, Light &bull; Mastery: Vex` },

  // ── MARTIAL MELEE — STANDARD (25 gp, Stock) ─────────────────────────────
  { name: "Battleaxe",    bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d8 Slashing &mdash; Versatile (1d10) &bull; Mastery: Topple` },
  { name: "Flail",        bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d8 Bludgeoning &bull; Mastery: Sap` },
  { name: "Longsword",    bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d8 Slashing &mdash; Versatile (1d10) &bull; Mastery: Sap` },
  { name: "Morningstar",  bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d8 Piercing &bull; Mastery: Sap` },
  { name: "Rapier",       bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d8 Piercing &mdash; Finesse &bull; Mastery: Vex` },
  { name: "Trident",      bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d8 Piercing &mdash; Thrown (20/60), Versatile (1d10) &bull; Mastery: Topple` },
  { name: "Warhammer",    bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d8 Bludgeoning &mdash; Versatile (1d10) &bull; Mastery: Push` },
  { name: "War Pick",     bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d8 Piercing &mdash; Versatile (1d10) &bull; Mastery: Sap` },
  { name: "Whip",         bulk: Bulk.STOCK,    cost: "25 gp", description: `<i>Martial Melee Weapon</i><br>1d4 Slashing &mdash; Finesse, Reach &bull; Mastery: Slow` },

  // ── MARTIAL MELEE — TWO-HANDED (40 gp, Stock) ───────────────────────────
  { name: "Glaive",       bulk: Bulk.STOCK,    cost: "40 gp", description: `<i>Martial Melee Weapon</i><br>1d10 Slashing &mdash; Heavy, Reach, Two-Handed &bull; Mastery: Graze` },
  { name: "Greataxe",     bulk: Bulk.STOCK,    cost: "40 gp", description: `<i>Martial Melee Weapon</i><br>1d12 Slashing &mdash; Heavy, Two-Handed &bull; Mastery: Cleave` },
  { name: "Greatsword",   bulk: Bulk.STOCK,    cost: "40 gp", description: `<i>Martial Melee Weapon</i><br>2d6 Slashing &mdash; Heavy, Two-Handed &bull; Mastery: Graze` },
  { name: "Halberd",      bulk: Bulk.STOCK,    cost: "40 gp", description: `<i>Martial Melee Weapon</i><br>1d10 Slashing &mdash; Heavy, Reach, Two-Handed &bull; Mastery: Cleave` },
  { name: "Lance",        bulk: Bulk.STOCK,    cost: "40 gp", description: `<i>Martial Melee Weapon</i><br>1d10 Piercing &mdash; Heavy, Reach, Two-Handed (unless mounted) &bull; Mastery: Topple` },
  { name: "Maul",         bulk: Bulk.STOCK,    cost: "40 gp", description: `<i>Martial Melee Weapon</i><br>2d6 Bludgeoning &mdash; Heavy, Two-Handed &bull; Mastery: Topple` },
  { name: "Pike",         bulk: Bulk.STOCK,    cost: "40 gp", description: `<i>Martial Melee Weapon</i><br>1d10 Piercing &mdash; Heavy, Reach, Two-Handed &bull; Mastery: Push` },

  // ── MARTIAL RANGED (40 gp, Stock) ───────────────────────────────────────
  { name: "Blowgun",        bulk: Bulk.STOCK,  cost: "40 gp", description: `<i>Martial Ranged Weapon</i><br>1 Piercing &mdash; Ammunition (25/100), Loading &bull; Mastery: Vex` },
  { name: "Hand Crossbow",  bulk: Bulk.STOCK,  cost: "40 gp", description: `<i>Martial Ranged Weapon</i><br>1d6 Piercing &mdash; Ammunition (30/120), Light, Loading &bull; Mastery: Vex` },
  { name: "Heavy Crossbow", bulk: Bulk.STOCK,  cost: "40 gp", description: `<i>Martial Ranged Weapon</i><br>1d10 Piercing &mdash; Ammunition (100/400), Heavy, Loading, Two-Handed &bull; Mastery: Push` },
  { name: "Longbow",        bulk: Bulk.STOCK,  cost: "40 gp", description: `<i>Martial Ranged Weapon</i><br>1d8 Piercing &mdash; Ammunition (150/600), Heavy, Two-Handed &bull; Mastery: Slow` },

  { _section: "Armor & Shields" },
  // ── ARMOUR ───────────────────────────────────────────────────────────────
  { name: "Shield",                bulk: Bulk.STOCK,  cost: "10 gp",   description: `+2 AC. You gain the Armor Class benefit of a Shield only if you have training with it.` },

  { name: "Padded Armor",          bulk: Bulk.STOCK,  cost: "5 gp",    description: `<i>Light Armor (1 min to don or doff)</i><br>AC 11 + Dex modifier. Stealth Disadvantage.` },
  { name: "Leather Armor",         bulk: Bulk.STOCK,  cost: "10 gp",   description: `<i>Light Armor (1 min to don or doff)</i><br>AC 11 + Dex modifier.` },
  { name: "Studded Leather Armor", bulk: Bulk.STOCK,  cost: "45 gp",   description: `<i>Light Armor (1 min to don or doff)</i><br>AC 12 + Dex modifier.` },

  { name: "Hide Armor",            bulk: Bulk.STOCK,  cost: "10 gp",   description: `<i>Medium Armor (5 min to don, 1 min to doff)</i><br>AC 12 + Dex modifier (max 2).` },
  { name: "Chain Shirt",           bulk: Bulk.STOCK,  cost: "50 gp",   description: `<i>Medium Armor (5 min to don, 1 min to doff)</i><br>AC 13 + Dex modifier (max 2).` },
  { name: "Scale Mail",            bulk: Bulk.STOCK,  cost: "50 gp",   description: `<i>Medium Armor (5 min to don, 1 min to doff)</i><br>AC 14 + Dex modifier (max 2). Stealth Disadvantage.` },
  { name: "Breastplate",           bulk: Bulk.STOCK,  cost: "400 gp",  description: `<i>Medium Armor (5 min to don, 1 min to doff)</i><br>AC 14 + Dex modifier (max 2).` },
  { name: "Half Plate",            bulk: Bulk.STOCK,  cost: "750 gp",  description: `<i>Medium Armor (5 min to don, 1 min to doff)</i><br>AC 15 + Dex modifier (max 2). Stealth Disadvantage.` },

  { name: "Ring Mail",             bulk: Bulk.STOCK,  cost: "30 gp",   description: `<i>Heavy Armor (10 min to don, 5 min to doff)</i><br>AC 14. Stealth Disadvantage.` },
  { name: "Chain Mail",            bulk: Bulk.STOCK,  cost: "75 gp",   description: `<i>Heavy Armor (10 min to don, 5 min to doff)</i><br>AC 16. Str 13 required. Stealth Disadvantage.` },
  { name: "Splint Armor",          bulk: Bulk.STOCK,  cost: "200 gp",  description: `<i>Heavy Armor (10 min to don, 5 min to doff)</i><br>AC 17. Str 15 required. Stealth Disadvantage.` },
  { name: "Full Plate",            bulk: Bulk.BULKY,  cost: "1500 gp", description: `<i>Heavy Armor (10 min to don, 5 min to doff)</i><br>AC 18. Str 15 required. Stealth Disadvantage.` },

  { _section: "Currency" },
  // ── CURRENCY ─────────────────────────────────────────────────────────────
  // Stacks up to 50 per packable slot. Use the counter to track quantity.
  { name: "Copper Pieces (CP)",   bulk: Bulk.PACKABLE, description: `1 cp = 1/10 sp = 1/100 gp`, variables: { coins: { value: 50, control: "both", min: 0, max: 50 } } },
  { name: "Silver Pieces (SP)",   bulk: Bulk.PACKABLE, description: `1 sp = 10 cp = 1/10 gp`,    variables: { coins: { value: 50, control: "both", min: 0, max: 50 } } },
  { name: "Gold Pieces (GP)",     bulk: Bulk.PACKABLE, description: `1 gp = 10 sp = 100 cp`,     variables: { coins: { value: 50, control: "both", min: 0, max: 50 } } },
  { name: "Platinum Pieces (PP)", bulk: Bulk.PACKABLE, description: `1 pp = 10 gp = 100 sp`,     variables: { coins: { value: 50, control: "both", min: 0, max: 50 } } },

  { _section: "Adventuring Gear" },
  // ── ADVENTURING GEAR ─────────────────────────────────────────────────────
  { name: "Rations (1 day)",     bulk: Bulk.PACKABLE, cost: "1 gp",  description: `Travel-ready food — jerky, dried fruit, hardtack, and nuts.` },
  { name: "Waterskin",           bulk: Bulk.PACKABLE,    cost: "1 gp",  description: `Holds up to 4 pints. If you don't drink sufficient water, you risk dehydration.` },
  { name: "Tinderbox",           bulk: Bulk.PACKABLE, cost: "5 sp",  description: `Contains flint, fire steel, and tinder. Bonus action to light a candle, lamp, lantern, or torch. Lighting any other fire takes 1 minute.` },
  { name: "Mirror",              bulk: Bulk.PACKABLE, cost: "5 sp",  description: `A handheld steel mirror — useful for personal cosmetics, peeking around corners, or reflecting light as a signal.` },
  { name: "Bell",                bulk: Bulk.PACKABLE, cost: "5 sp",  description: `When rung as a Utilize action, produces a sound heard up to 60 feet away.` },
  { name: "Chalk (5 pieces)",    bulk: Bulk.PACKABLE, cost: "5 sp",  description: `Used to mark surfaces. Expend a piece to leave a visible mark.`, variables: { pieces: { value: 5, control: "plusminus", min: 0, max: 5 } } },
  { name: "Parchment (5 sheets)",bulk: Bulk.PACKABLE, cost: "5 sp",  description: `Each sheet holds about 250 handwritten words.`, variables: { sheets: { value: 5, control: "plusminus", min: 0, max: 5 } } },
  { name: "Ink and Pen",         bulk: Bulk.PACKABLE, cost: "5 sp",  description: `An ink pen and a 1-ounce bottle of ink — enough to write about 500 pages.` },
  { name: "Torch",               bulk: Bulk.PACKABLE, cost: "5 sp",  description: `Burns for 1 hour, casting Bright Light in a 20-foot radius and Dim Light for an additional 20 feet. Can be used as a simple melee weapon (1 Fire damage on a hit).`, variables: { torches: { value: 6, control: "plusminus", min: 0, max: 6 } } },
  { name: "Whistle / Horn",      bulk: Bulk.PACKABLE, cost: "1 gp",  description: `Produces a sound that can be heard up to 600 feet away (whistle) or across great distances (horn). Utilize action to blow.` },
  { name: "Shovel",              bulk: Bulk.PACKABLE,    cost: "1 gp",  description: `Working for 1 hour, you can use a Shovel to dig a hole 5 feet on each side in soil or similar material.` },
  { name: "Rope (50ft)",         bulk: Bulk.PACKABLE,    cost: "1 gp",  description: `As a Utilize action, tie a knot with a DC Dexterity (Sleight of Hand) check. Burst with a successful Strength (Athletics) check. Can bind a Grappled, Incapacitated, or Restrained creature.` },
  { name: "Oil Flask",           bulk: Bulk.PACKABLE, cost: "2 gp",  description: `Fuel for lanterns. Bonus action to douse a creature or object; on a hit, target takes 5 Fire damage if ignited before the start of your next turn. One flask fuels a lantern for 6 hours.`, variables: { flasks: { value: 5, control: "plusminus", min: 0, max: 5 } } },
  { name: "Manacles",            bulk: Bulk.PACKABLE,    cost: "2 gp",  description: `As a Utilize action, bind a Grappled, Incapacitated, or Restrained creature within 5 feet (DC Dexterity (Sleight of Hand) check). While bound, the creature has Disadvantage on attack rolls and can't cast spells with somatic components. DC 20 Strength (Athletics) or DC 15 Dexterity (Sleight of Hand) to escape.` },
  { name: "Grappling Hook",      bulk: Bulk.PACKABLE, cost: "2 gp",  description: `As a Utilize action, throw up to 50 feet to catch on a railing, ledge, or similar (DC Dexterity (Acrobatics) check). Attach a rope to climb.` },
  { name: "Crowbar",             bulk: Bulk.PACKABLE,    cost: "2 gp",  description: `Using a Crowbar gives you Advantage on Strength checks where its leverage can be applied.` },
  { name: "Lantern, Hooded",     bulk: Bulk.PACKABLE,    cost: "5 gp",  description: `Burns oil as fuel. Casts Bright Light in a 30-foot radius and Dim Light for an additional 30 feet. Bonus action to lower the hood (Dim Light in a 5-foot radius) or raise it again.` },
  { name: "Satchel",             bulk: Bulk.STOCK,    cost: "2 gp",  description: `Holds gear. Does not count toward carry capacity.`, noCarry: true, containerRows: 1 },
  { name: "Backpack",            bulk: Bulk.STOCK,    cost: "5 gp",  description: `Holds up to 30 pounds within 1 cubic foot. Does not count toward carry capacity.`, noCarry: true, containerRows: 4 },
  { name: "Saddlebag",           bulk: Bulk.STOCK,    cost: "5 gp",  description: `Attaches to a mount. Holds gear and does not count toward your carry capacity.`, noCarry: true, containerRows: 2 },
  { name: "Ammunition Cache",    bulk: Bulk.STOCK,    cost: "15 gp", description: `One cache per ammunition type. Represents a full, regularly resupplied supply — no need to track individual rounds. Must be worn to access. Thrown, magical, or otherwise unique ammunition must still be tracked separately; a cache of their kind holds up to 8.`, variables: { count: { value: 8, control: "plusminus", min: 0, max: 8 } } },
  { name: "Ball Bearings",       bulk: Bulk.PACKABLE, cost: "1 gp",  description: `As a Utilize action, spill to cover a level 10-foot-square area within 10 feet. Creatures entering the area must succeed on a DC 10 Dexterity saving throw or fall Prone. Takes 10 minutes to collect.` },
  { name: "Caltrops",            bulk: Bulk.PACKABLE, cost: "1 gp",  description: `As a Utilize action, spread to cover a 5-foot-square area within 5 feet. Creatures entering must succeed on a DC 10 Dexterity saving throw or take 1 Piercing damage and have Speed reduced to 0 until the start of their next turn.` },
  { name: "Basic Poison",        bulk: Bulk.PACKABLE, cost: "5 gp",  description: `As a Bonus Action, coat one weapon or up to three pieces of ammunition. A creature that takes Piercing or Slashing damage from the poisoned weapon takes an extra 1d4 Poison damage. Retains potency for 1 minute or until its first hit.` },
  { name: "Holy Water",          bulk: Bulk.PACKABLE, cost: "5 gp",  description: `When you take the Attack action, you can replace one attack with throwing this flask at a creature within 20 feet. Target makes a DC Dexterity saving throw or takes 2d8 Radiant damage if it is a Fiend or Undead.` },
  { _section: "Alchemist Items" },
  { name: "Acid",                bulk: Bulk.PACKABLE, cost: "8 gp",  description: `When you take the Attack action, replace one attack with throwing this vial at a target within 20 feet. Target makes a DC Dexterity saving throw or takes 2d6 Acid damage.` },
  { name: "Alchemist's Fire",    bulk: Bulk.PACKABLE, cost: "8 gp",  description: `When you take the Attack action, replace one attack with throwing this flask at a target within 20 feet. Target makes a DC Dexterity saving throw or takes 1d4 Fire damage and starts burning. A burning creature takes 1d4 Fire damage at the start of each of its turns; a Utilize action ends the burning.` },
  { name: "Bottled Lightning",   bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a Utilize action, open the Bottled Lightning. A bolt of lightning in a 30-foot-long, 1-foot-wide line blasts in a direction you choose. If the lightning would strike a creature, that creature must make a DC 13 Dexterity saving throw, taking 1d8 Lightning damage on a failed save; the lightning stops if it hits a creature. The item is destroyed.` },
  { name: "Flask of Floods",     bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a Utilize action, open the Flask of Floods. Water pours out as though you used the geyser option of a <i>decanter of endless water</i>. The item is destroyed.` },
  { name: "Smoke Bomb",          bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a Utilize action, ignite and throw a Smoke Bomb at a location you can see within 20ft. The bomb creates a 10-foot-radius Sphere of smoke there. The area is Heavily Obscured and lasts until the start of your next turn, or until a wind of moderate or greater speed disperses it. The item is destroyed.` },
  { name: "Winter's Breath",     bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a Utilize action, open the Winter's Breath. Creatures in a 15-foot cone from you must succeed on a DC 13 Constitution saving throw or take 1d4 Cold damage and have their speed reduced by 10ft until the start of your next turn. The item is destroyed.` },
  { name: "Oil of Acid",         bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a bonus action, coat a weapon or three pieces of ammunition with this oil to have it deal an extra 1d6 Acid damage. Once applied, the oil retains potency for 1 minute or until its damage is dealt, whichever comes first.` },
  { name: "Oil of Cold",         bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a bonus action, coat a weapon or three pieces of ammunition with this oil to have it deal an extra 1d6 Cold damage. Once applied, the oil retains potency for 1 minute or until its damage is dealt, whichever comes first.` },
  { name: "Oil of Fire",         bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a bonus action, coat a weapon or three pieces of ammunition with this oil to have it deal an extra 1d6 Fire damage. Once applied, the oil retains potency for 1 minute or until its damage is dealt, whichever comes first.` },
  { name: "Oil of Lightning",    bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a bonus action, coat a weapon or three pieces of ammunition with this oil to have it deal an extra 1d6 Lightning damage. Once applied, the oil retains potency for 1 minute or until its damage is dealt, whichever comes first.` },
  { name: "Oil of Poison",       bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a bonus action, coat a weapon or three pieces of ammunition with this oil to have it deal an extra 1d6 Poison damage. Once applied, the oil retains potency for 1 minute or until its damage is dealt, whichever comes first.` },
  { name: "Oil of Thunder",      bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a bonus action, coat a weapon or three pieces of ammunition with this oil to have it deal an extra 1d6 Thunder damage. Once applied, the oil retains potency for 1 minute or until its damage is dealt, whichever comes first.` },
  { name: "Healing Potion",      bulk: Bulk.PACKABLE, cost: "8 gp",  description: `As a Bonus Action, drink or administer to a creature within 5 feet. The creature regains 2d4 + 2 Hit Points.` },


  { _section: "Consumable Magical Curios" },
  { _rarity: "Common" },
  { name: "Identifying Scroll",      bulk: Bulk.PACKABLE, cost: "15 gp",  description: `A scroll inscribed with the Identify spell. Cast it without requiring a spell slot or material components to learn the properties of one magic item or one spell affecting a creature.` },
  { name: "Sticky Finger",           bulk: Bulk.PACKABLE, cost: "15 gp",  description: `Inserted into a non-magical lock, this thin metal finger immediately grows filaments, reshaping itself into a matching key. Once transformed, it remains in that shape permanently.` },
  { name: "Raven Charm",             bulk: Bulk.PACKABLE, cost: "30 gp",  description: `This small statuette can be used to cast <i>animal messenger</i>, transforming it into a raven for the spell. Once the spell ends, the raven transforms back into the figurine, then becomes non-magical.` },
  { name: "Ammunition of Capture",   bulk: Bulk.PACKABLE, cost: "30 gp",  description: `You can forgo the attack roll when you attack with this ammunition to have the target make a Dexterity saving throw (DC 13) as if it were affected by a <i>net</i> (Escape DC 13; AC 13; 10 HP). The ammunition is destroyed.` },
  { name: "Ammunition of Tracking",  bulk: Bulk.PACKABLE, cost: "30 gp",  description: `When this ammunition hits, it transforms into a small invisible mark. For 24 hours you know the target's distance and direction. The ammunition is destroyed.` },
  { name: "Ammunition of Grappling", bulk: Bulk.PACKABLE, cost: "30 gp",  description: `When fired, this ammunition becomes immovable when it strikes. It can hold up to 500 pounds and has a small ring for attaching rope. It can be removed with a DC 20 Strength (Athletics) check, destroying it in the process.` },
  { name: "Bubble Token",            bulk: Bulk.PACKABLE, cost: "60 gp",  description: `This small metal disk is inscribed with the image of a jet of bubbles. As a magic action, choose up to 5 creatures underwater you can see within 60ft; they gain 1 hour of additional air before suffocating while they remain underwater. The token's magic is expended, whereupon the disk becomes nonmagical.` },
  { name: "Feather Token",           bulk: Bulk.PACKABLE, cost: "60 gp",  description: `This small metal disk is inscribed with the image of a feather. When you fall at least 20 feet while the token is on your person, you descend 60 feet per round and take no damage from falling. The token's magic is expended after you land, whereupon the disk becomes nonmagical.` },
  { name: "Balm of Disguise",        bulk: Bulk.PACKABLE, cost: "60 gp",  description: `You can apply this balm to gain the effects of the <i>disguise self</i> spell (DC 13). The effect ends early if you are fully submerged in water.` },
  { name: "Shield Wall",             bulk: Bulk.STOCK, cost: "60 gp",  description: `As a magic action, you can plant this shield, causing it to unfurl into a 5ft wide, 5ft tall wall (AC 15, 10 hit points). It provides half cover, or full cover if prone beside it, and can be used to block openings. When placed, it becomes nonmagical and cannot be recovered.` },
  { name: "Seed of Climbing",        bulk: Bulk.PACKABLE, cost: "60 gp",  description: `As a magic action, you can plant this seed adjacent to a wall. The seed immediately sprouts a thick network of vines that grows up to 30 feet high and 5 feet wide along the wall. Immediately after planting the seed, you can choose to climb onto the vines as they grow, near instantly ascending to the top.` },

  // Waning Wands (Uncommon — cannot be recharged)
  { name: "Waning Wand of Magic Missile", bulk: Bulk.PACKABLE, cost: "60 gp/charge", description: `<i>Waning wand — cannot be recharged</i><br>Expend a charge to cast Magic Missile (3 darts). Each charge spent increases the level by 1 (max 5th level).`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Waning Wand of Web",           bulk: Bulk.PACKABLE, cost: "60 gp/charge", description: `<i>Waning wand — cannot be recharged</i><br>Expend a charge to cast Web (DC 13).`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Waning Wand of Darkness",      bulk: Bulk.PACKABLE, cost: "60 gp/charge", description: `<i>Waning wand — cannot be recharged</i><br>Expend a charge to cast Darkness.`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Waning Wand of Paralysis",     bulk: Bulk.PACKABLE, cost: "60 gp/charge", description: `<i>Waning wand — cannot be recharged</i><br>Expend a charge to cast Hold Person (DC 13).`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Waning Wand of Wonder",        bulk: Bulk.PACKABLE, cost: "60 gp/charge", description: `<i>Waning wand — cannot be recharged</i><br>Expend a charge to trigger a random magical effect (roll on the Wand of Wonder table).`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },

  // Uncommon
  { name: "Gem of Recall",         bulk: Bulk.PACKABLE, cost: "120 gp", description: `You can attune this gem to a single item no larger than 3 feet in any dimension by holding it against the object for 10 minutes. Once attuned, you can shatter the gem as a bonus action to summon the item instantly into your hand or at your feet. If the object is more than 1 mile away, the item isn't summoned. The gem is destroyed when used.` },
  { name: "Deathrite Coins",       bulk: Bulk.PACKABLE, cost: "120 gp", description: `Placing these gold coins over a corpse's eyes casts <i>speak with dead</i> on it. The coins then lose their magic.` },
  { name: "Dust of Revealing",     bulk: Bulk.PACKABLE, cost: "120 gp", description: `As a magical action, you can scatter this dust in a 10-foot emanation. For 1 minute, it glows faintly, revealing magical auras and ending invisibility and illusions within the area and on affected creatures. The dust is consumed on use.` },
  { name: "Dust of Disappearance", bulk: Bulk.PACKABLE, cost: "120 gp", description: `When you take a Utilize action to throw the dust into the air, you and each creature and object within a 10-foot emanation have the <i>invisible</i> condition for 2d4 minutes. The duration is the same for all subjects, and the dust is consumed when its magic takes effect. Immediately after an affected creature makes an attack roll, deals damage, or casts a spell, the <i>invisible</i> condition ends for that creature.` },
  { name: "Salt of Binding",       bulk: Bulk.PACKABLE, cost: "120 gp", description: `You can spend 1 minute spreading this salt in a 5-foot-radius circle. When a Celestial, Elemental, Fey, Fiend, or Undead enters the circle, or touches its edge, if you are within 60ft of the circle, you can use your reaction to activate it. The area is then affected by the <i>magic circle</i> spell (DC 13), targeting the triggering creature's type for 1 hour. The salt is consumed on use.` },
  { name: "Tonic of Potency",      bulk: Bulk.PACKABLE, cost: "120 gp", description: `This bottle contains 6 drops. As an action, you can add up to 3 drops to any of the following items: alchemist's fire, basic poison, bottled lightning, flask of floods, holy water, oil of elemental damage, and winter's breath. When the item deals damage, deal an additional damage die for each drop added (maximum 3).`, variables: { drops: { value: 6, control: "plusminus", min: 0, max: 6 } } },
  { name: "Cloudy Hag Eye",        bulk: Bulk.PACKABLE, cost: "120 gp", description: `This functions as a <i>Hag Eye</i>. When used, there is a 10 percent chance it instead emits a loud, mocking cackle audible within 300 feet and disintegrates.` },
  { name: "Flicker Dagger",        bulk: Bulk.STOCK,    cost: "120 gp", description: `When you throw this weapon, you can teleport to the targeted space or a space adjacent to it as long as you can see the location and it is unoccupied. Immediately after, the dagger is destroyed.` },
  { name: "Deep-Haul Harpoon",     bulk: Bulk.STOCK,    cost: "60 gp/charge", description: `When you find this spear it has 1d3 charges. When thrown, you can expend a charge to return it to your hand, and if you hit a target that is large or smaller, pull them up to 15 feet straight toward yourself. When this spear has no charges, it becomes non-magical.`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Weapon of Silence",     bulk: Bulk.STOCK, cost: "60 gp/charge", description: `When you find this weapon it has 1d3 charges. When it deals damage, you can expend a charge to make its target create no sound (as though within the area of the <i>silence</i> spell) until the end of your next turn. When this weapon has no charges, it becomes non-magical.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS }, charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Luster Weapon",         bulk: Bulk.STOCK,    cost: "60 gp/charge", description: `When you find this weapon, it has 1d3 charges. This gilded weapon bears a small, magical mouth. You can spend 10 minutes feeding it 40gp worth of gold to expend a charge and make it a +1 weapon for 24 hours. When all charges are expended, the weapon becomes a worthless non-magical weapon.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS }, charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },

  // Rare
  { name: "Waning Wand of Lightning Bolt", bulk: Bulk.PACKABLE, cost: "120 gp/charge", description: `<i>Waning wand — cannot be recharged</i><br>Expend a charge to cast Lightning Bolt (DC 15, 8d6).`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Waning Wand of Fireball",       bulk: Bulk.PACKABLE, cost: "120 gp/charge", description: `<i>Waning wand — cannot be recharged</i><br>Expend a charge to cast Fireball (DC 15, 8d6).`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Waning Wand of Polymorph",      bulk: Bulk.PACKABLE, cost: "120 gp/charge", description: `<i>Waning wand — cannot be recharged</i><br>Expend a charge to cast Polymorph (DC 15).`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Ammunition of Spell Storing",   bulk: Bulk.PACKABLE, cost: "+60 gp",        description: `One of the following spells can be stored in this piece of ammunition by casting it at its minimum spell level: Magic Missile, Entangle, Thunderwave, Fog Cloud, Spike Growth, Silence, Darkness, Daylight, Lightning Bolt, Fireball. When found, there is a 50 percent chance it already contains a stored spell. As a magic action, fire it from a ranged weapon; the stored spell is cast from the point of impact (DC 13). If the spell is a line or cone, you choose the direction. The ammunition is destroyed on use.` },
  { name: "Undead Paw",                    bulk: Bulk.PACKABLE, cost: "120 gp/charge", description: `This shriveled undead hand has 1d4+1 fingers when found. As a magical action, you can expend a finger to cast <i>Animate Dead</i>. The undead created cannot be controlled and is hostile toward all living creatures. When all fingers are gone, the paw loses its magic.`, variables: { fingers: { value: 5, control: "plusminus", min: 0, max: 5 } } },
  { name: "Ammunition of Slaying",         bulk: Bulk.PACKABLE, cost: "120 gp",        description: `When you find this ammunition it is of one of the types below. When it deals damage to a creature of its type, deal an additional 2d6 Force damage. After dealing its extra damage, the ammunition becomes nonmagical.<br><b>D6 — Creature Type</b><br>1 Elemental &bull; 2 Monstrosity &bull; 3 Aberration &bull; 4 Fey &bull; 5 Fiend &bull; 6 Undead` },
  { name: "Spear of Lightning",            bulk: Bulk.STOCK,    cost: "120 gp",        description: `You can have this spear deal Lightning damage. When you throw this weapon at a target no farther than 60 feet, instead the weapon turns into a 5-foot-wide bolt of lightning between you and the target. Each other creature in the line makes a Dexterity saving throw (DC 13), taking 4d6 Lightning damage on a failed save or half as much on a successful one. Immediately after, the weapon is destroyed.` },
  { name: "Glyph Scroll",                  bulk: Bulk.PACKABLE, cost: "240 gp",        description: `By spending 10 minutes holding this scroll to a surface, you can cast <i>glyph of warding</i>. The scroll is destroyed when used.` },
  { name: "Witch's Ladder",                bulk: Bulk.PACKABLE, cost: "240 gp",        description: `When you first find this braid it is woven into one of the wards below. When the ward's trigger occurs, the braid unfastens and its wearer is affected by the associated spell (DC 13). The braid then becomes non-magical.<br><b>D3 — Ward — Trigger — Spell</b><br>1 <b>Mind</b> You are charmed, frightened, or incapacitated by hostile magic &mdash; <i>dispel magic</i><br>2 <b>Body</b> You become incapacitated &mdash; <i>sanctuary</i><br>3 <b>Spirit</b> You are the target of hostile divination magic &mdash; <i>nondetection</i>` },
  { name: "Death-Knell Weapon",            bulk: Bulk.STOCK,    cost: "120 gp/charge", description: `<i>(requires attunement)</i><br>When you find this weapon it has 1d3 charges. While it has a charge it is a +1 magical weapon. When an attack from this weapon is a critical hit, it loses a charge and deals an additional die of the weapon's damage. When it has no charges, it becomes non-magical.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS }, charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Builder's Impossible Belt",     bulk: Bulk.PACKABLE, cost: "120 gp/charge", description: `This belt has 1d3 + 2 embroidered patches, each showing a construction item. As a magical action, you can pull off a patch and throw it into an unoccupied space within 10 feet. It becomes the depicted nonmagical item or fixture. Roll a d6 for each patch when found:<br><b>d6 Patch:</b> 1 Portable battering ram &bull; 2 15-foot wooden ladder &bull; 3 Wooden bridge 5ft × 15ft &bull; 4 Stone barricade 5ft × 15ft &bull; 5 Tunnel 5ft × 5ft × 15ft, placeable on a wall or the ground &bull; 6 Iron door 10ft × 10ft barred on one side, placeable in an opening<br>Once used, a patch cannot be restored. When all patches are gone, the belt loses its magic.`, variables: { patches: { value: 5, control: "plusminus", min: 0, max: 5 } } },
  { name: "Black Sandglass",               bulk: Bulk.PACKABLE, cost: "240 gp/charge", description: `This sandglass has 3 charges. When your turn would end, you can use your reaction to expend one charge and activate it. Everything reverts to before you took your turn, except the sandglass' charges. Once it has no charges, it becomes mundane and loses its magic.`, variables: { cracks: { value: 3, control: "plusminus", min: 0, max: 3 } } },

  // Very Rare
  { name: "Elemental Gem (Air)",    bulk: Bulk.PACKABLE, cost: "500 gp",  description: `Crush to summon an Air Elemental that serves you for 1 hour or until reduced to 0 HP.` },
  { name: "Elemental Gem (Water)",  bulk: Bulk.PACKABLE, cost: "500 gp",  description: `Crush to summon a Water Elemental that serves you for 1 hour or until reduced to 0 HP.` },
  { name: "Elemental Gem (Fire)",   bulk: Bulk.PACKABLE, cost: "500 gp",  description: `Crush to summon a Fire Elemental that serves you for 1 hour or until reduced to 0 HP.` },
  { name: "Elemental Gem (Earth)",  bulk: Bulk.PACKABLE, cost: "500 gp",  description: `Crush to summon an Earth Elemental that serves you for 1 hour or until reduced to 0 HP.` },
  { name: "Chalk of Passwall",      bulk: Bulk.PACKABLE, cost: "500 gp",  description: `Spending 10 minutes drawing a doorway with this chalk creates a passage as though you cast <i>passwall</i>. The chalk is expended when used.` },
  { name: "Tears of Celestia",      bulk: Bulk.PACKABLE, cost: "500 gp",  description: `This pendant holds 6 drops of healing elixir. Applying drops to a creature within reach restores 4d4 + 4 hit points each. Alternatively, spending 2 drops casts <i>lesser restoration</i>; spending 5 drops casts <i>greater restoration</i>. Once all drops are used, the pendant becomes nonmagical.`, variables: { drops: { value: 6, control: "plusminus", min: 0, max: 6 } } },
  { name: "Deck of Wonder",         bulk: Bulk.PACKABLE, cost: "1800 gp", description: `*` },

  { _section: "Gems of Enchantment" },
  // ── GEMS OF ENCHANTMENT ──────────────────────────────────────────────────
  // Uncommon (500 gp) — applied to a weapon
{ name: "Gem of Elemental Resistance (Acid)",     bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to an item. Thereafter, you have resistance to Acid damage while that item is within your reach.` },
  { name: "Gem of Elemental Resistance (Thunder)",  bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to an item. Thereafter, you have resistance to Thunder damage while that item is within your reach.` },
  { name: "Gem of Elemental Resistance (Lightning)",bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to an item. Thereafter, you have resistance to Lightning damage while that item is within your reach.` },
  { name: "Gem of Elemental Resistance (Cold)",     bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to an item. Thereafter, you have resistance to Cold damage while that item is within your reach.` },
  { name: "Gem of Elemental Resistance (Fire)",     bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to an item. Thereafter, you have resistance to Fire damage while that item is within your reach.` },
  { name: "Gem of Elemental Resistance (Necrotic)", bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to an item. Thereafter, you have resistance to Necrotic damage while that item is within your reach.` },
  { name: "Gem of Returning Weapon",   bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, the weapon returns to your hand immediately after it is thrown to make a ranged attack.` },
  { name: "Gem of Shifting Weapon",    bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to an item. Thereafter, as a bonus action you can change its form to one other simple or martial weapon (chosen when you attach the gem) or back.` },
  { name: "Gem of Elemental Weapon (Acid)",    bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, you can have the weapon deal Acid damage.` },
  { name: "Gem of Elemental Weapon (Thunder)", bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, you can have the weapon deal Thunder damage.` },
  { name: "Gem of Elemental Weapon (Lightning)",bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, you can have the weapon deal Lightning damage.` },
  { name: "Gem of Elemental Weapon (Cold)",    bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, you can have the weapon deal Cold damage.` },
  { name: "Gem of Elemental Weapon (Fire)",    bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, you can have the weapon deal Fire damage.` },
  { name: "Gem of Elemental Weapon (Radiant)", bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, you can have the weapon deal Radiant damage.` },
  { name: "Gem of Ghost-Strike",       bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, treat it as a <i>Ghost-Strike Weapon</i>.` },
  { name: "Gem of Aquatic Weapon",     bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, treat it as an <i>Aquatic Weapon</i>.` },
  { name: "Gem of Accuracy",           bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, when you have advantage on an attack roll with the weapon using Dexterity, Intelligence, Wisdom, or Charisma, you can reroll one of the dice once.` },
  { name: "Gem of Mastery",            bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to a weapon. Thereafter, while attached, you have proficiency with that weapon and can use its weapon mastery.` },

  // Rare (800 gp) — hidden
  { name: "Gem of Resilience",    bulk: Bulk.PACKABLE, cost: "800 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> When you first find this gem, it is one of the types below. You can attach it to an item. Thereafter, you have +1 to saving throws of the gem's type while it is within reach.<br><b>D6 Gemstone — Saving Throws:</b> 1-2 Unyielding Spirit (Constitution and Charisma) &bull; 3-4 Swift Mind (Dexterity and Intelligence) &bull; 5-6 Dauntless Will (Strength and Wisdom)` },
  { name: "Gem of Warning",       bulk: Bulk.PACKABLE, cost: "800 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> When you first find this gem, it is one of the types below. You can attach it to an item. Thereafter, while that item is within your reach, you and allies within 30 feet have advantage on initiative rolls against creatures of the gem's type.<br><b>D6 Gemstone — Creature Type:</b> 1 Tourmaline (Elemental) &bull; 2 Ruby (Monstrosity) &bull; 3 Amethyst (Aberration) &bull; 4 Moonstone (Fey) &bull; 5 Obsidian (Fiend) &bull; 6 Jet (Undead)` },
  { name: "Gem of Excess",        bulk: Bulk.PACKABLE, cost: "800 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> When attuned, it occupies two attunement slots. You can attach this gem to a weapon. Thereafter, the first time you hit with the weapon each turn, you can deal an additional 1d4 damage of its damage type.` },
  { name: "Gem of Spell Storing", bulk: Bulk.PACKABLE, cost: "800 gp", description: `<i>(requires attunement)</i><br>This is a <i>Gem of Enchantment</i>. <i>You can spend 10 minutes attaching this gem to an item it specifies. It can be removed for 30gp as a downtime activity.</i> You can attach this gem to an item. Thereafter, it functions as a Ring of Spell Storing that can store one 1st level spell.` },

  { _section: "Magical Curios" },
  // ── MAGICAL CURIOS ───────────────────────────────────────────────────────
  // Common
  { name: "Gem of False Value",      bulk: Bulk.PACKABLE, cost: "1 cp",   description: `Appears to be a valuable gemstone worth 100 gp or more, but is magically worthless. A creature that examines it must succeed on a DC 15 Intelligence (Arcana) check to identify the ruse.` },
  // Common (240 gp)
  { name: "Cloak of Billowing",        bulk: Bulk.STOCK,    cost: "240 gp", description: `As a bonus action, you can cause this cloak to billow dramatically.` },
  { name: "Charlatan's Die",           bulk: Bulk.PACKABLE, cost: "240 gp", description: `Whenever you roll this six-sided die, you can control which number it rolls.` },
  { name: "Pole of Collapsing",        bulk: Bulk.PACKABLE,    cost: "240 gp", description: `While holding this 10-foot pole, you can use a bonus action to speak a command word and cause it to collapse into a 1-foot rod. Speaking the command word again causes the rod to extend back into a pole.` },
  { name: "Staff of Birdcalls",        bulk: Bulk.STOCK,    cost: "240 gp", description: `This wooden staff has 10 charges. While holding it, you can use an action to expend 1 charge to create one of the following sounds within 60 feet: a finch's chirp, raven's caw, duck's quack, owl's hoot, turkey's gobble, seagull's cry, hummingbird's hum, or chicken's cluck. The staff regains 1d6+4 charges daily at dawn. If the last charge is expended, roll a d20; on a 1, the staff vanishes in a burst of feathers.`, variables: { charges: { value: 10, control: "plusminus", min: 0, max: 10 } } },
  { name: "Horn of Silent Alarm",      bulk: Bulk.PACKABLE, cost: "240 gp", description: `This horn has 4 charges. When you use an action to blow it, one creature of your choice within 600 feet that isn't deafened hears the horn's blare — no other creature hears it. The horn regains 1d4 charges daily at dawn.`, variables: { charges: { value: 4, control: "plusminus", min: 0, max: 4 } } },
  { name: "Cloak of Many Fashions",    bulk: Bulk.STOCK,    cost: "240 gp", description: `As a bonus action, you can change the style, color, and apparent quality of this cloak. It can duplicate the appearance of other cloaks but not their magical properties.` },
  { name: "Rope of Mending",           bulk: Bulk.STOCK,    cost: "240 gp", description: `You can cut this 50-foot coil of hempen rope into any number of pieces, then use an action to speak a command word and cause the pieces to knit back together. The pieces must be in contact with each other and not otherwise in use.` },
  { name: "Ring of Magic Sensitivity", bulk: Bulk.PACKABLE, cost: "240 gp", description: `This ring glows faintly when held to a magic item or object.` },
  { name: "Boots of False Tracks",     bulk: Bulk.PACKABLE,    cost: "240 gp", description: `While wearing these boots, you can choose to have them leave tracks like those of a different kind of humanoid of the same size.` },
  { name: "Ruby of the War Mage",      bulk: Bulk.PACKABLE, cost: "240 gp", description: `Pressing this 1-inch ruby against a weapon for 10 minutes attaches it, allowing you to use that weapon as a spellcasting focus. You can detach it as an action, or it is lost if the weapon is destroyed.` },
  { name: "Veteran's Cane",            bulk: Bulk.STOCK,    cost: "240 gp", description: `While holding this cane, you can use a bonus action to speak its command word, transforming it into a shortsword (losing its magic), or speak the command word again to return it to a cane.` },
  { name: "Moontouched Weapon",        bulk: Bulk.STOCK,    cost: "240 gp", description: `In darkness, this weapon sheds moonlight, creating bright light in a 10-foot radius and dim light for an additional 10 feet. It counts as a magical weapon for the purpose of overcoming resistances and immunities.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },

  // Uncommon (500 gp)
  { name: "Pigskin Purse",               bulk: Bulk.STOCK,    cost: "500 gp", description: `This snouted pouch can store up to 2,500 gp. Once you have carried it for 24 hours, it bonds with you. While separated from it, you know its distance and direction and can command it to squeal, audible out to 300 feet, until it is returned or you command it to stop.` },
  { name: "Prismatic Ring",              bulk: Bulk.PACKABLE, cost: "500 gp", description: `This opalescent glass ring functions as a spellcasting focus. While wearing it, you can reshape cone spells you cast into 5-foot-wide lines twice the cone's range, or line spells into cones with half the line's length.` },
  { name: "Gloves of Eavesdropping",     bulk: Bulk.PACKABLE, cost: "500 gp", description: `While wearing these gloves, you can place your hand on a solid surface no more than 10 feet thick to hear through it as if you were on the other side.` },
  { name: "Purifying Waterskin",         bulk: Bulk.PACKABLE, cost: "500 gp", description: `This waterskin is always cool to the touch; liquid placed inside and food it pours upon becomes free of disease and poison. Drinking from it as a bonus action lets you make poison and disease saving throws with advantage for 1 minute.` },
  { name: "Meteor Shield",               bulk: Bulk.STOCK,    cost: "500 gp", description: `This shield can be used as a thrown weapon (range 60/120). On a hit, it deals 1d8 + your Strength modifier fire damage.` },
  { name: "Ring of the Locksmith",       bulk: Bulk.PACKABLE, cost: "500 gp", description: `You can use a magic action and tap an object with this ring to cast <i>knock</i> or <i>arcane lock</i> on it. This property can't be used again until you finish a long rest.` },
  { name: "Brawler's Gloves",            bulk: Bulk.PACKABLE, cost: "500 gp", description: `As a bonus action, you can cock your arms to activate these gloves. For 1 hour, you gain the benefits of the Tavern Brawler feat. This property can't be used again until you finish a short or long rest.` },
  { name: "Dungeon Crawler's Rosaries",  bulk: Bulk.PACKABLE, cost: "500 gp", description: `These rosaries have 3 charges. You can expend a charge and spend 10 minutes meditating while holding these rosaries to attune to a magic item. All charges are restored when you finish a long rest.`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Mask of Mimicry",             bulk: Bulk.PACKABLE,    cost: "500 gp", description: `While wearing this mask you can mimic any sounds you have heard, including voices. A creature can tell the sounds they are imitations with a successful DC 13 Wisdom (Insight) check.` },
  { name: "Death Mask of Bated Breath",  bulk: Bulk.PACKABLE,    cost: "500 gp", description: `While wearing this mask, you can use it as a spellcasting focus and you don't need to breathe.` },
  { name: "Veteran's Gorget",            bulk: Bulk.PACKABLE,    cost: "500 gp", description: `Immediately after rolling initiative, you can swap your result with one willing ally in the same combat.` },
  { name: "Mantle of the Eft",           bulk: Bulk.STOCK,    cost: "500 gp", description: `<i>(requires attunement)</i><br>While wearing this cloak, you can hold your breath underwater for 1 hour, and have a swim speed equal to your speed.` },
  { name: "Armor of Scuttling",          bulk: Bulk.STOCK,    cost: "500 gp", description: `<i>(requires attunement)</i><br>While wearing this armor, you can move at your normal speed while prone or when moving through a narrow opening sized for a smaller creature. Also, you having the prone condition does not give creatures advantage on attack rolls against you.` },
  { name: "Shield of Legends",           bulk: Bulk.STOCK,    cost: "500 gp", description: `<i>(requires attunement)</i><br>When you perform a heroic deed, you can have the moment magically etched into the shield over the next minute. The shield holds up to ten etchings; when full, the oldest fades to make room for a new one. While wielding the shield, you have advantage on saving throws against being frightened.` },
  { name: "Boots of Pouncing",           bulk: Bulk.PACKABLE,    cost: "500 gp", description: `<i>(requires attunement)</i><br>You can spend 10 feet of movement and use a bonus action to jump up to 30 feet. This property can't be used again until you finish a long rest.` },
  { name: "Booming Belt",                bulk: Bulk.PACKABLE,    cost: "500 gp", description: `<i>(requires attunement)</i><br>As a magic action, you can shout a sentence audible out to 600 feet. As part of the same action, you can also cast <i>thunderwave</i> (DC 13). Once used, this property can't be used again until you finish a long rest.` },
  { name: "Bull-Headed Belt",            bulk: Bulk.PACKABLE,    cost: "500 gp", description: `<i>(requires attunement)</i><br>When you are moved against your will, you can use your reaction to remain in place instead. This property can't be used again until you finish a short or long rest.` },
  { name: "Craven Armor",                bulk: Bulk.STOCK,    cost: "500 gp", description: `<i>(requires attunement)</i><br>While wearing this armor, when you take the Disengage or Dodge action, your speed increases by 10ft until the end of the turn.` },
  { name: "Mantle of Shadows",           bulk: Bulk.STOCK,    cost: "500 gp", description: `<i>(requires attunement)</i><br>While wearing this cloak and in darkness or dim light, you can take the hide action even if you are being directly observed.` },
  { name: "Catseye Charm",               bulk: Bulk.PACKABLE, cost: "500 gp", description: `<i>(requires attunement)</i><br>While wearing this charm, you have a climbing speed of 20 feet and when you make a Dexterity (Acrobatics) check, treat a d20 roll of 9 or lower as a 10.` },
  { name: "Cloak of Many Eyes",          bulk: Bulk.STOCK,    cost: "500 gp", description: `<i>(requires attunement)</i><br>This cloak has 3 charges. As a bonus action, you can expend a charge to cause unblinking eyes to open across it. For 10 minutes, when you make a Wisdom (Perception) check, treat a d20 roll of 9 or lower as a 10. When you finish a long rest, regain all charges.`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },
  { name: "Boots of Continuous Step",    bulk: Bulk.PACKABLE,    cost: "500 gp", description: `<i>(requires attunement)</i><br>When you would fall, you can use your reaction to activate these boots. Then, until the end of your turn, you can move through the air at your current elevation as though walking on solid ground. This property can't be used again for 1 minute.` },
  { name: "Spellsword's Vambrace",       bulk: Bulk.PACKABLE,    cost: "500 gp", description: `<i>(requires attunement by a spellcaster)</i><br>While wearing this vambrace, you know the <i>true strike</i> cantrip. When a creature provokes an opportunity attack from you, you can cast <i>true strike</i> targeting it instead of making the attack.` },

  // Rare (800 gp)
  { name: "Container of Sharing",        bulk: Bulk.STOCK,    cost: "800 gp", description: `These magically linked containers share a single inventory. If the containers are more than 1-mile apart, their contents appears as a featureless black void and cannot be modified. The number of item slots available is equal to that of the smallest linked container.` },
  { name: "Warded Armor",                bulk: Bulk.STOCK,    cost: "800 gp", description: `While wearing this armor, you cannot be charmed, cursed, or possessed.` },
  { name: "Circlet of Telepathy",        bulk: Bulk.PACKABLE,    cost: "800 gp", description: `While wearing this circlet, you can speak telepathically with any creature within 60 feet of you. The creature can respond telepathically in the same manner.` },
  { name: "Amulet of Telekinesis",       bulk: Bulk.PACKABLE, cost: "800 gp", description: `While wearing this amulet you know the <i>mage hand</i> spell. You cast it without verbal or somatic components, and can make the spectral hand <i>invisible</i> when you cast it. The spell's spellcasting ability is your Intelligence.` },
  { name: "Wisplight",                   bulk: Bulk.PACKABLE, cost: "800 gp", description: `This is a <i>driftglobe</i>, except it follows within 5 feet, and its commands must be given within that range.` },
  { name: "Cloak of the Fence",          bulk: Bulk.STOCK,    cost: "800 gp", description: `<i>(requires attunement)</i><br>You can store up to 4 item slots of items in this cloak, turning them into symbols sewn upon it. These items are weightless and can be drawn as a bonus action. This cloak appears nonmagical to divination magic, such as <i>detect magic</i>.` },
  { name: "Mirror Shield",               bulk: Bulk.STOCK,    cost: "800 gp", description: `<i>(requires attunement)</i><br>While donning this shield, when you roll a 20 on a saving throw against a spell, or a creature rolls a 1 when targeting you with a spell attack, the source suffers the effect of the spell instead.` },
  { name: "Cape of the Butterfly",       bulk: Bulk.STOCK,    cost: "800 gp", description: `<i>(requires attunement)</i><br>As a magic action, you can unfurl this cape, revealing vivid eye patterns. A creature with Intelligence 5 or less within 60ft that can see makes an Intelligence saving throw (DC 13). If it fails, it has the <i>frightened</i> and <i>incapacitated</i> conditions for 1 minute; it tries to move as far from you as it can on its turns. This effect ends early if the creature takes damage. This property can't be used again until you finish a long rest.` },
  { name: "Mawed Shield",                bulk: Bulk.STOCK,    cost: "800 gp", description: `<i>(requires attunement)</i><br>When a large or smaller creature within 5 feet rolls a 1 on a melee attack roll against you, you can use your reaction to have the shield bite it; it is dealt 1d8 piercing damage and grappled (escape DC 13). While grappled, it takes 1d8 piercing damage at the end of each of its turns. You can choose to end the grapple on your turn.` },
  { name: "Boots of Retracing Step",     bulk: Bulk.PACKABLE,    cost: "800 gp", description: `<i>(requires attunement)</i><br>As a magic action, you can create a shadowy set of footprints at your current location. Within the next minute, you can use a bonus action to teleport to that space, leaving behind a brief illusory trail. If the destination is occupied, the effect fails. Once used, this property can't be used again until you finish a long rest.` },
  { name: "Cloak of Stillness",          bulk: Bulk.STOCK,    cost: "800 gp", description: `<i>(requires attunement)</i><br>This cloak has 3 charges; as a magic action you can expend a charge to become invisible for 1 minute. You remain invisible until you take damage or act in any way. When you finish a long rest, regain all charges.`, variables: { charges: { value: 3, control: "plusminus", min: 0, max: 3 } } },

  // Very Rare (1800 gp)
  { name: "Chest of Ambulation",         bulk: Bulk.BULKY,    cost: "1800 gp", description: `This chest has a dozen small feet. It has a speed of 30 feet and follows its owner within 30 feet unless commanded otherwise. It obeys verbal commands and holds up to 12 item slots of equipment.<br><b>Sentient.</b> The chest is sentient. It has 90 feet normal vision, Int: 8, Wis: 8, Cha: 8. It does not speak but understands Common and communicates via body language (stomping, shuffling).` },
  { name: "Tome of Forgotten Secrets",   bulk: Bulk.PACKABLE,    cost: "1800 gp", description: `You can spend 8 hours studying this tome and burn incense worth 100 gp to cast <i>legend lore</i>. The lore revealed is limited to information that was known at least a century ago.<br><b>Sentient.</b> The book is sentient. It speaks by changing the writing upon its pages, and can hear out to 30 feet, Int: 19, Wis: 15, Cha: 12.` },
  { name: "Amulet of Reaper's Mercy",    bulk: Bulk.PACKABLE, cost: "1800 gp", description: `<i>(requires attunement)</i><br>While wearing this amulet, when you make a death saving throw, a roll of 19 or 20 causes you to regain 1 hit point. Also, the first time you are reduced to 0 hit points after each long rest, you don't suffer exhaustion.` },
  { name: "Ring of Realms",              bulk: Bulk.PACKABLE, cost: "1800 gp", description: `<i>(requires attunement)</i><br>When you first find this ring, it is inset with one of the gems below. As a magic action you can cast <i>invisibility</i> and <i>see invisibility</i> on yourself. The effects only apply to creatures of the gem's creature type. You can't use this property again until you finish a long rest.<br><b>D6 Gemstone — Creature Type:</b> 1 Diamond (Human) &bull; 2 Ruby (Monstrosity) &bull; 3 Amethyst (Aberration) &bull; 4 Moonstone (Fey) &bull; 5 Obsidian (Fiend) &bull; 6 Jet (Undead)` },

  { _section: "Magical Weapons" },
  // ── MAGICAL WEAPONS ──────────────────────────────────────────────────────
  // Uncommon (500 gp)
  { name: "Aquatic Weapon",          bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>While submerged treat this as a +1 weapon, and it suffers no penalties for being underwater.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Ghost-Strike Weapon",     bulk: Bulk.STOCK, cost: "500 gp",  description: `This weapon can strike targets on the Ethereal Plane and ignores resistances of creatures with <i>incorporeal movement</i>.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Titan-Slayer Weapon",     bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>When you attack a huge or larger creature with this weapon, treat it as a +1 weapon.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Mage-Slayer Weapon",      bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>This weapon's attacks ignore the AC bonuses of spells. When you damage a concentrating spellcaster with this weapon, they have disadvantage on their concentration saving throw.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Weapon of Slaying",       bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>When you first find this weapon, it is one of the types below. When attacking that creature type, treat it as a +1 weapon.<br><b>D6 Creature Type:</b> 1 Elemental &bull; 2 Monstrosity &bull; 3 Aberration &bull; 4 Fey &bull; 5 Fiend &bull; 6 Undead`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Crestfall Weapon",        bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>While bloodied you can treat this as a +1 weapon.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Branding Weapon",         bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>When you hit a creature with this weapon you can choose to brand it. Until the end of your next turn, the target sheds bright light in a 5-foot radius, and it can't benefit from the <i>invisible</i> condition.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Envious Weapon",          bulk: Bulk.STOCK, cost: "500 gp",  description: `When wielded with another <i>light</i> weapon, this weapon copies its magical properties and effects. Charges and uses are shared between both weapons. As a bonus action, you can transform this weapon into the kind of weapon in your other hand, or back.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Keen Weapon",             bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>When you roll a 19 or 20 on an attack roll for this weapon, the hit is a critical hit.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Fell Weapon",             bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>When you score a critical hit with this weapon, you can roll two additional weapon damage dice and add them to the extra damage.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Striving Weapon",         bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>Once each turn, you can reroll one damage die for an attack made with this weapon.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Boundless Weapon",        bulk: Bulk.STOCK, cost: "500 gp",  description: `<i>(requires attunement)</i><br>When you roll the maximum result on a weapon damage die from this weapon, roll an additional weapon damage die and add it as extra damage.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },

  // Rare (800 gp)
  { name: "Patient Weapon",          bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>When you take the attack action, you can forgo one attack. If you do, the next attack you make with this weapon before the end of your next turn is made with advantage, even if you would have disadvantage.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Brutal Weapon",           bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>When you take the attack action, you can forgo advantage on one attack to have that attack deal an additional 1d8 damage of the weapon's damage type.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Vigilant Weapon",         bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>When you take the attack action with this weapon, you can forgo one attack. Then, if a creature moves into your reach before the start of your next turn, you can make an opportunity attack against it using this weapon.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Shifting Weapon",         bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>As a <i>free object interaction</i> you can change this weapon's form to any simple or martial melee weapon. It is made of a single piece of unique metal, is immune to effects that corrode items, and cannot be silvered.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Weapon of Echoes",        bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>A second Weapon of Echoes can be attuned without occupying an attunement slot. When this weapon hits a target already struck by a Weapon of Echoes this round, deal an additional 1d4 thunder damage.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Weapon of Mastery",       bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>You gain proficiency with this weapon and can use its weapon mastery. If you already could, choose one other mastery when you attune to this weapon. You can use the chosen mastery with this weapon. Only one weapon mastery property can apply to an attack.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Fatal Weapon",            bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>After dealing damage with this weapon, if the target has hit points equal to or less than the maximum result of this weapon's damage dice, they die.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Mage Blade",              bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement by a spellcaster)</i><br>As a bonus action, you can expend a 2nd level or higher spell slot to treat this sword as a +1 weapon that deals Force damage until your next long rest.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Ever-Fanged Blade",       bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>This weapon is immune to effects that corrode items. Also, a poison coating it doesn't lose potency over time. As a bonus action, you can have a poison you coated this weapon with in the past bleed from the ouroboros symbol etched in its blade, magically coating it. This property can't be used again until you finish a long rest.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Blink Weapon",            bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>While holding this weapon, you can cast <i>misty step</i>. Once used, this property can't be used again until you finish a long rest. Immediately after you teleport no more than 30ft and make an attack with this weapon, you can teleport back to your previous space if it is unoccupied.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Elemental Sword",         bulk: Bulk.STOCK, cost: "800 gp",  description: `<i>(requires attunement)</i><br>When found, this hilt is one of the below types. As a bonus action, while holding the hilt, you can form a longsword from elemental energy of that type. While formed, it deals that damage type, sheds bright light in a 15-foot radius and dim light for an additional 15 feet, and has the <i>finesse</i> property. It remains formed until you dismiss it as a bonus action, or you drop or stow it.<br><b>D6 Damage Type:</b> 1 Acid &bull; 2 Thunder &bull; 3 Lightning &bull; 4 Cold &bull; 5 Fire &bull; 6 Radiant`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Weapon of Slots (2 Gems)",bulk: Bulk.STOCK, cost: "800 gp",  description: `The total attunement cost of gems attached to this weapon is reduced by 1 (to a minimum of 1). You can remove a gem attached from this weapon for no cost.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },

  // Very Rare (1800 gp)
  { name: "Sword of Life Stealing",  bulk: Bulk.STOCK, cost: "1800 gp", description: `<i>(requires attunement)</i><br>When you attack a creature with this weapon and roll a 20 on the d20 for the attack roll, that target takes an extra 15 Necrotic damage if it isn't a Construct or an Undead, and you gain temporary hit points equal to the amount of Necrotic damage taken.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Weapon of Celestia",      bulk: Bulk.STOCK, cost: "1800 gp", description: `<i>(requires attunement)</i><br>When you hit a Fiend or Undead with this weapon, it deals Radiant damage and the creature is treated as vulnerable to the weapon's damage dice. When planted in the ground, after 1 hour, this weapon creates the effect of the <i>hallow</i> spell at its location. The effect ends when the weapon is uprooted.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Frost Brand",             bulk: Bulk.STOCK, cost: "1800 gp", description: `<i>(requires attunement)</i><br>While holding this weapon, you have resistance to fire damage. In freezing temperatures, the weapon sheds bright light in a 10-foot radius and dim light for an additional 10 feet. The first time each turn you hit with this weapon, deal an extra 1d4 Cold damage. When you draw this weapon, you can extinguish all nonmagical flames within 30 feet of yourself. Once used, this property can't be used again for 1 hour.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Flame-Tongue",            bulk: Bulk.STOCK, cost: "1800 gp", description: `<i>(requires attunement)</i><br>While holding this weapon, you can use a bonus action and speak a command word to ignite it. While ignited, it sheds bright light in a 40-foot radius, dim light for an additional 40 feet, and the first time each turn you hit with this weapon, deal an extra 1d6 Fire damage. It remains ignited until you use a bonus action to issue the command again or drop, stow, or sheathe the weapon.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Vorpal Sword",            bulk: Bulk.STOCK, cost: "1800 gp", description: `<i>(requires attunement)</i><br>This weapon ignores resistance to Slashing damage. When you roll a 20 on the d20 for an attack roll with this weapon against a creature, if the target has 40 hit points or fewer and has a head that can be severed, it is decapitated. If not dead or decapitated, it takes an additional 20 Slashing damage.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Weapon of Notches",       bulk: Bulk.STOCK, cost: "1800 gp", description: `<i>(requires attunement)</i><br>This weapon bears 1d4-1 notches carved into its surface when found. Each time you kill a creature with it, a new notch magically appears.<br><b>Notches Ability:</b> 5 — Immune to corrosion &bull; 10 — Sentient (Int/Wis/Cha 10, communicates by transmitting emotion) &bull; 15 — Speaks and understands the languages of its attuned wielder &bull; 20 — Becomes a +1 weapon &bull; 25 — Once per long rest, ask it to recall a memory from a creature it has killed; answers up to three questions.`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Sentient Weapon",         bulk: Bulk.STOCK, cost: "1800 gp", description: `<i>(requires attunement)</i><br>When you first find this sentient weapon its form, senses, and communication type are determined below. Int: 10, Wis: 10, Cha: 10. Its personality and goals are determined by the GM.<br><b>D6 Weapon:</b> 1-2 Blended Weapon &bull; 3-4 Rare/Very Rare Weapon &bull; 5-6 Questing Weapon<br><b>D6 Senses:</b> 1-2 Perceives through its wielder &bull; 3-4 Hearing and normal vision 30ft &bull; 5-6 Hearing and darkvision 30ft<br><b>D6 Communication:</b> 1-2 Transmits emotion &bull; 3-4 Telepathy with wielder &bull; 5-6 Speaks and understands one language`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },
  { name: "Questing Weapon",         bulk: Bulk.STOCK, cost: "1800 gp", description: `<i>(requires attunement)</i><br>A poem, story, or map etched into this weapon tells of a quest to unlock its power. Upon completing the quest, it becomes a weapon from below.<br><b>D6 Weapon:</b> 1-2 Blended Weapon &bull; 3-4 Rare/Very Rare Weapon &bull; 5-6 Sentient Weapon`, variables: { weapon: { control: "select", value: "Longsword", options: WEAPON_OPTIONS } } },

  { _section: "Tools & Kits" },
  // ── TOOLKITS ─────────────────────────────────────────────────────────────
  { name: "Camp Supplies",         bulk: Bulk.STOCK, cost: "10 gp", description: `Tent, bedroll, fire-starting supplies, and cooking gear for one person. Provides a comfortable long rest in the wilderness.` },
  { name: "Climber's Tools",       bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Strength</i><br>Boot tips, gloves, pitons, and a harness. As a Utilize action, anchor yourself so you can't fall more than 25 feet from the anchor point or move more than 25 feet from it without undoing the anchor as a Bonus Action.` },
  { name: "Smith's Tools",         bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Strength</i><br>Utilize: Pry open a door or container (DC 20). Craft: melee weapons, medium/heavy armor, metal adventuring gear.` },
  { name: "Mason's Tools",         bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Strength</i><br>Utilize: Chisel a symbol or hole in stone (DC 10). Craft: Block and Tackle.` },
  { name: "Woodcarver's Tools",    bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Dexterity</i><br>Utilize: Carve a pattern in wood (DC 10). Craft: clubs, ranged weapons, ammunition, arcane/druidic focuses, ink pen.` },
  { name: "Leatherworker's Tools", bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Dexterity</i><br>Utilize: Add a design to a leather item (DC 10). Craft: sling, whip, leather armors, backpack, pouch, quiver, waterskin.` },
  { name: "Weaver's Tools",        bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Dexterity</i><br>Utilize: Mend a tear in clothing (DC 10), or sew a Tiny design (DC 10). Craft: padded armor, bedroll, blanket, clothes, net, rope, tent.` },
  { name: "Scribe's Supplies",     bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Intelligence</i><br>Ink, pens, and fine parchment for copying texts and scribing scrolls. Utilize: Produce a convincing written document (DC 10). Craft: written materials and spell scrolls.` },
  { name: "Painter's Supplies",    bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Wisdom</i><br>Utilize: Paint a recognizable image of something you've seen (DC 10). Craft: Druidic Focus, Holy Symbol.` },
  { name: "Jeweler's Tools",       bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Intelligence</i><br>Utilize: Discern a gem's value (DC 15). Craft: Arcane Focus, Holy Symbol.` },
  { name: "Cook's Utensils",       bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Wisdom</i><br>Utilize: Improve food's flavor (DC 10), or detect spoiled or poisoned food (DC 15). Craft: Rations.` },
  { name: "Healer's Kit",          bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Wisdom</i><br>10 uses. As a Utilize action, expend one use to stabilize an Unconscious creature at 0 Hit Points without a Medicine check.`, variables: { uses: { value: 10, control: "plusminus", min: 0, max: 10 } } },
  { name: "Poisoner's Kit",        bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Intelligence</i><br>Utilize: Detect a poisoned object (DC 10). Craft: Basic Poison.` },
  { name: "Herbalism Kit",         bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Intelligence</i><br>Utilize: Identify a plant (DC 10). Craft: Antitoxin, Candle, Healer's Kit, Potion of Healing.` },
  { name: "Glassblower's Tools",   bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Intelligence</i><br>Utilize: Discern what a glass object held in the past 24 hours (DC 15). Craft: Glass Bottle, Magnifying Glass, Spyglass, Vial.` },
  { name: "Potter's Tools",        bulk: Bulk.STOCK, cost: "15 gp", description: `<i>Ability: Intelligence</i><br>Utilize: Discern what a ceramic object held in the past 24 hours (DC 15). Craft: Jug, Lamp.` },
  { name: "Thieves' Tools",        bulk: Bulk.STOCK, cost: "25 gp", description: `<i>Ability: Dexterity</i><br>Utilize: Pick a lock (DC 15), or disarm a trap (DC 15).` },
  { name: "Tinker's Tools",        bulk: Bulk.STOCK, cost: "25 gp", description: `<i>Ability: Dexterity</i><br>Utilize: Assemble a Tiny item from scrap that falls apart in 1 minute (DC 20). Craft: Bell, Lanterns, Hunting Trap, Lock, Manacles, Mirror, Shovel, Signal Whistle, Tinderbox.` },
  { name: "Alchemist's Supplies",  bulk: Bulk.STOCK, cost: "25 gp", description: `<i>Ability: Intelligence</i><br>Utilize: Identify a substance (DC 15), or start a fire (DC 15). Craft: Acid, Alchemist's Fire, Oil, Paper, Perfume.` },
  { name: "Disguise Kit",          bulk: Bulk.STOCK, cost: "25 gp", description: `<i>Ability: Charisma</i><br>Utilize: Apply makeup (DC 10). Craft: Costume. While wearing a costume crafted with this kit, you have Advantage on checks to impersonate the person or type of person it represents.` },
  { name: "Navigator's Tools",     bulk: Bulk.STOCK, cost: "75 gp", description: `<i>Ability: Wisdom</i><br>Utilize: Plot a course (DC 10), or determine your position by stargazing (DC 15).` },


  { _section: "Mounts" },
  // ── MOUNTS ───────────────────────────────────────────────────────────────
  { name: "Donkey / Mule",  bulk: Bulk.BULKY, cost: "20 gp",  description: `A sturdy beast of burden. Can carry heavy loads over long distances. Speed 40 ft.` },
  { name: "Draft Horse",    bulk: Bulk.BULKY, cost: "50 gp",  description: `A large, powerful horse bred for hauling. Speed 40 ft. Can pull a wagon or plow.` },
  { name: "Riding Horse",   bulk: Bulk.BULKY, cost: "75 gp",  description: `A well-trained horse suitable for travel and combat. Speed 60 ft.` },
  { name: "Warhorse",       bulk: Bulk.BULKY, cost: "400 gp", description: `A combat-trained horse. Speed 60 ft. Can be used as a mount in battle without being spooked.` },
  { name: "Sled Dog",       bulk: Bulk.BULKY, cost: "50 gp",  description: `<i>Exotic Mount</i><br>A trained sled dog. Four sled dogs are required to pilot a Sled. Speed 40 ft.` },
  { name: "Camel",          bulk: Bulk.BULKY, cost: "50 gp",  description: `<i>Exotic Mount</i><br>A desert-adapted mount. Speed 50 ft. Can go without water for up to two weeks.` },
  { name: "Axe Beak",       bulk: Bulk.BULKY, cost: "100 gp", description: `<i>Exotic Mount</i><br>A large flightless bird with a heavy bill. Speed 50 ft. Can be trained as a mount.` },
  { name: "Elephant",       bulk: Bulk.BULKY, cost: "600 gp", description: `<i>Exotic Mount</i><br>A massive, intelligent beast. Speed 40 ft. Can carry enormous loads and serve in battle.` },

  { _section: "Vehicles" },
  // ── CARRIAGES ────────────────────────────────────────────────────────────
  { name: "Sled",           bulk: Bulk.BULKY, cost: "20 gp",  description: `24 item slots. Requires 4 sled dogs to pilot. Encumbrance limit is 10× the mounts' carry capacity.` },
  { name: "Wagon (Small)",  bulk: Bulk.BULKY, cost: "75 gp",  description: `200 item slots. Requires 1 large mount to pilot. Encumbrance limit is 10× the mount's carry capacity.` },
  { name: "Wagon (Large)",  bulk: Bulk.BULKY, cost: "100 gp", description: `400 item slots. Requires 2 large mounts to pilot. Encumbrance limit is 10× the mounts' carry capacity.` },

  { _section: "Valuables" },
  // ── MISC ITEMS ────────────────────────────────────────────────────────────
  // Gems and Jewelry: use the value counter to track worth in gp
  { name: "Gems",    bulk: Bulk.PACKABLE, description: `Precious or semi-precious stones. Use the value counter to track their total worth in gp.`, variables: { "gp value": { value: 0, control: "both", min: 0, max: 9999 } } },
  { name: "Jewelry", bulk: Bulk.PACKABLE, description: `Rings, necklaces, bracelets, or other ornaments. Use the value counter to track their total worth in gp.`, variables: { "gp value": { value: 0, control: "both", min: 0, max: 9999 } } },

  // Ingots — fixed value, Stock
  { name: "Copper Ingot",        bulk: Bulk.STOCK,  cost: "125 gp",       description: `A refined copper ingot worth 125 gp.` },
  { name: "Iron / Silver Ingot", bulk: Bulk.STOCK,  cost: "250 gp",       description: `A refined iron or silver ingot worth 250 gp.` },
  { name: "Gold Ingot",          bulk: Bulk.STOCK,  cost: "500 gp",       description: `A refined gold ingot worth 500 gp.` },

  // Nuggets — variable value range, Bulky
  { name: "Copper Nugget",       bulk: Bulk.BULKY,  cost: "50–125 gp",    description: `A raw copper nugget. Worth 50–125 gp depending on size and purity.` },
  { name: "Iron / Silver Nugget",bulk: Bulk.BULKY,  cost: "100–250 gp",   description: `A raw iron or silver nugget. Worth 100–250 gp depending on size and purity.` },
  { name: "Gold Nugget",         bulk: Bulk.BULKY,  cost: "200–500 gp",   description: `A raw gold nugget. Worth 200–500 gp depending on size and purity.` },

  { _section: "Potions" },
  // ── POTIONS ───────────────────────────────────────────────────────────────
  // Common (60 gp)
  { name: "Potion of Darkvision",       bulk: Bulk.PACKABLE, cost: "60 gp",  description: `<i>Common potion</i><br>Bonus Action to drink. Gain Darkvision out to 60 feet for 1 hour (if you already have Darkvision, its range extends by 60 feet).` },
  { name: "Potion of Water Breathing",  bulk: Bulk.PACKABLE, cost: "60 gp",  description: `<i>Common potion</i><br>Bonus Action to drink. Breathe underwater for 1 hour.` },
  { name: "Potion of Climbing",         bulk: Bulk.PACKABLE, cost: "60 gp",  description: `<i>Common potion</i><br>Bonus Action to drink. Gain a Climb Speed equal to your Speed and Advantage on Strength (Athletics) checks for 1 hour.` },
  { name: "Potion of Animal Friendship",bulk: Bulk.PACKABLE, cost: "60 gp",  description: `<i>Common potion</i><br>Bonus Action to drink. Casts Animal Friendship (no save) on up to three Beasts for 1 hour.` },
  // Uncommon (60 gp)
  { name: "Potion of Elemental Breath (Fire)",      bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. For 1 minute, use an Action to exhale a 30-foot cone dealing 4d6 Fire damage (DC 13 Dex save for half).` },
  { name: "Potion of Elemental Breath (Acid)",      bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. For 1 minute, use an Action to exhale a 30-foot cone dealing 4d6 Acid damage (DC 13 Dex save for half).` },
  { name: "Potion of Elemental Breath (Poison)",    bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. For 1 minute, use an Action to exhale a 30-foot cone dealing 4d6 Poison damage (DC 13 Dex save for half).` },
  { name: "Potion of Elemental Breath (Lightning)", bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. For 1 minute, use an Action to exhale a 30-foot cone dealing 4d6 Lightning damage (DC 13 Dex save for half).` },
  { name: "Potion of Elemental Breath (Cold)",      bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. For 1 minute, use an Action to exhale a 30-foot cone dealing 4d6 Cold damage (DC 13 Dex save for half).` },
  { name: "Philter of Love",            bulk: Bulk.PACKABLE, cost: "60 gp",  description: `<i>Uncommon potion</i><br>Bonus Action to drink. The next time you see a creature within 10 minutes, you have the Charmed condition toward that creature for 1 hour.` },
  { name: "Potion of Resistance (Fire)",      bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. Resistance to Fire damage for 1 hour.` },
  { name: "Potion of Resistance (Cold)",      bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. Resistance to Cold damage for 1 hour.` },
  { name: "Potion of Resistance (Acid)",      bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. Resistance to Acid damage for 1 hour.` },
  { name: "Potion of Resistance (Poison)",    bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. Resistance to Poison damage for 1 hour.` },
  { name: "Potion of Resistance (Lightning)", bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. Resistance to Lightning damage for 1 hour.` },
  { name: "Potion of Resistance (Necrotic)",  bulk: Bulk.PACKABLE, cost: "60 gp", description: `<i>Uncommon potion</i><br>Bonus Action to drink. Resistance to Necrotic damage for 1 hour.` },
  { name: "Potion of Greater Healing",  bulk: Bulk.PACKABLE, cost: "60 gp",  description: `<i>Uncommon potion</i><br>Bonus Action to drink. Regain 4d4 + 4 Hit Points.` },
  // Rare (120 gp)
  { name: "Potion of Mind Reading",     bulk: Bulk.PACKABLE, cost: "120 gp", description: `<i>Rare potion</i><br>Bonus Action to drink. Gain the effect of the Detect Thoughts spell (DC 13) for 10 minutes, no Concentration required.` },
  { name: "Potion of Growth",           bulk: Bulk.PACKABLE, cost: "120 gp", description: `<i>Rare potion</i><br>Bonus Action to drink. You are enlarged as per the Enlarge/Reduce spell for 1 minute (no concentration). Your size doubles, Strength checks and saves have Advantage, and your weapons deal an extra 1d4 damage.` },
  { name: "Elixir of Health",           bulk: Bulk.PACKABLE, cost: "120 gp", description: `<i>Rare potion</i><br>Bonus Action to drink. Cures all diseases and neutralizes all poisons. Ends the Blinded, Deafened, Paralyzed, and Poisoned conditions.` },
  { name: "Potion of Superior Healing", bulk: Bulk.PACKABLE, cost: "120 gp", description: `<i>Rare potion</i><br>Bonus Action to drink. Regain 8d4 + 8 Hit Points.` },
  // Very Rare (180–240 gp)
  { name: "Potion of Invisibility",     bulk: Bulk.PACKABLE, cost: "180 gp", description: `<i>Very Rare potion</i><br>Bonus Action to drink. Become Invisible for 1 hour. The effect ends early if you make an attack roll or cast a spell.` },
  { name: "Potion of Gaseous Form",     bulk: Bulk.PACKABLE, cost: "180 gp", description: `<i>Very Rare potion</i><br>Bonus Action to drink. You transform into a misty cloud as per the Gaseous Form spell for 1 hour (no concentration).` },
  { name: "Potion of Speed",            bulk: Bulk.PACKABLE, cost: "240 gp", description: `<i>Very Rare potion</i><br>Bonus Action to drink. The Haste spell is cast on you for 1 minute (no concentration).` },
  { name: "Potion of Heroism",          bulk: Bulk.PACKABLE, cost: "240 gp", description: `<i>Very Rare potion</i><br>Bonus Action to drink. Gain 10 Temporary Hit Points and the Frightened condition cannot be imposed on you for 1 hour.` },
  { name: "Potion of Flying",           bulk: Bulk.PACKABLE, cost: "240 gp", description: `<i>Very Rare potion</i><br>Bonus Action to drink. Gain a Fly Speed equal to your Speed for 1 hour. If you're aloft when the effect ends, you fall.` },
  { name: "Potion of Giant Strength",   bulk: Bulk.PACKABLE, cost: "240 gp", description: `<i>Very Rare potion</i><br>Bonus Action to drink. Strength score becomes 21 for 1 hour (higher if already greater).` },
  { name: "Oil of Etherealness",        bulk: Bulk.PACKABLE, cost: "240 gp", description: `<i>Very Rare oil</i><br>Action to apply. You and your equipment become Ethereal for 1 hour, able to pass through solid matter and see into the Material Plane but not be seen or affected by it.` },
  { name: "Potion of Vitality",         bulk: Bulk.PACKABLE, cost: "240 gp", description: `<i>Very Rare potion</i><br>Bonus Action to drink. Remove all levels of Exhaustion and cure all diseases and poisons. For the next 24 hours, whenever you roll a Hit Die to recover Hit Points, use the maximum value.` },

];
